export const products = [
    {
        code: "001",
        name: "Ik hef mijn ogen - Psalm 121",
        description:
            "Deze witte enkele kaart Ik hef mijn ogen op naar de bergen vanwaar mijn Hulp komen zal uit psalm 121 wordt met envelop geleverd.",
        category: "Bijbeltekst",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        new: true,
        favorite: true,
        tokens: [
            "Bijbeltekst kaart",
            "Bijbeltekst Statenvertaling",
            "Kaart Statenvertaling",
            "Kaart SV",
            "Kaart Psalm 121 vers 1",
            "Kaart Psalm 121",
            "Kaartje Bijbeltekst",
            "Kaartje Psalm",
            "Ik hef mijn ogen op naar de bergen vanwaar Mijn hulp komen zal",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten",
        ],
    },
    {
        code: "002",
        name: "Van hartjes gefeliciteerd",
        description: "Deze witte enkele kaart Van hartjes gefeliciteerd wordt met envelop geleverd. ",
        category: "Verjaardag",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: true,
        waterColor: false,
        new: true,
        favorite: true,
        tokens: [
            "Kaart Van hartjes gefeliciteerd",
            "Kaart verjaardag",
            "Kaart gefeliciteerd",
            "Kaart gefeliciteerd vrouw",
            "Kaart meisje",
            "Kaart hartjes",
            "Kaart met hartjes",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten ",
        ],
    },
    {
        code: "003",
        name: "Hieperdepiep Hoera",
        description: "Deze witte enkele kaart Hierdepiep Hoera wordt met envelop geleverd.",
        category: "Verjaardag",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: true,
        waterColor: false,
        new: true,
        favorite: false,
        tokens: [
            "Kaart Hierdepiep Hoera",
            "Kaart verjaardag",
            "Kaart gefeliciteerd",
            "Kaart gefeliciteerd vrouw",
            "Kaart gefeliciteerd man",
            "Kaart Hoera",
            "Kaart kinderen",
            "Kaart meisje",
            "Kaart jongen",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten ",
        ],
    },
    {
        code: "004",
        name: "Hoera, een kleintje!",
        description: "Deze witte enkele kaart Hoera, een kleintje! met lieve giraffe wordt met envelop geleverd.",
        category: "Geboorte",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: true,
        waterColor: true,
        new: true,
        favorite: false,
        tokens: [
            "Kaart Hoera, een kleintje!",
            "Kaart geboorte",
            "Kaart geboorte unisex",
            "Kaart geboorte jongen",
            "Kaart geboorte meisje",
            "Kaart Een kleintje",
            "Kaart kind geboren",
            "Kaart aquarel",
            "Kaart giraffe",
            "Kaart giraf",
            "Kaart kind met giraffe",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten ",
        ],
    },
    {
        code: "005",
        name: "Hoera, een meisje!",
        description: "Deze witte enkele kaart Hoera, een meisje! wordt met envelop geleverd.",
        category: "Geboorte",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: true,
        waterColor: false,
        new: true,
        favorite: false,
        tokens: [
            "Kaart Hoera, een meisje!",
            "Kaart geboorte",
            "Kaart geboorte meisje",
            "Kaart kind geboren",
            "Kaart meisje",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten ",
        ],
    },
    {
        code: "006",
        name: "Gefeliciteerd met jullie trouwdag",
        description: "Deze witte enkele kaart Gefeliciteerd met jullie trouwdag wordt met envelop geleverd.",
        category: "Huwelijk",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        new: true,
        favorite: false,
        tokens: [
            "Kaart gefeliciteerd met jullie trouwdag",
            "Kaart trouwdag",
            "Kaart bruiloft",
            "Kaart trouwerij",
            "Kaart huwelijk",
            "Kaart huwelijksjubileum",
            "Kaart getrouwd",
            "Kaart bruidspaar",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten ",
        ],
    },
    {
        code: "007",
        name: "Een dikke knuffel door de brievenbus",
        description: "Deze witte enkele kaart Een dikke knuffel door de brievenbus wordt met envelop geleverd.",
        category: "Beterschap/Sterkte",
        price: 1.5,
        format: "A6",
        color: "Wit",
        paper: "Natuurkarton 350g",
        envelope: true,
        doubleSided: false,
        roundCorners: true,
        waterColor: false,
        new: true,
        favorite: true,
        tokens: [
            "Kaart Een dikke knuffel door de brievenbus",
            "Kaart knuffel",
            "Kaart beterschap",
            "Kaart sterkte",
            "Kaart zomaar",
            "Kaartje verzenden",
            "Kaart door brievenbus",
            "Lettering Marije",
            "Marije Hoegée",
            "Handlettering",
            "Handgeletterde kaarten ",
        ],
    },
];

export default products;
