
export const PRODUCT_IMAGES_PREFIX = "/Productcode - ";
export const PRODUCT_IMAGES_FILE_TYPE = ".jpg";
export const products = [
    {
        code: "001",
        name: "Kaars Oranje/Turquoise ",
        description:
            "Deze zelfgemaakte kaars heeft een unieke combinatie van turquoise en oranje, die in elkaar overlopen en een prachtig visueel effect creëren wanneer ze brandt. De kaars is zowel decoratief als functioneel en is ideaal om een gezellige sfeer te creëren in huis.",
        category: "Kaarsen",
        price: 1.5,
        format: "A6",
        color: "turquoise - Oranje",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: true,
        new: true,
        tokens: [
            "Kaars",
            "Zomerse Kaars",
            "Kaars turquoise",
            "Kaars Oranje",
            "Kaars Oranje met turquoise",
            "Kleurrijke kaars",
        ],
    },
    {
        code: "002",
        name: "Kaars Turquoise/Paarse ",
        description:
        "Deze zelfgemaakte kaars heeft een unieke combinatie van Turquoise en Paars, die in elkaar overlopen en een prachtig visueel effect creëren wanneer ze brandt. De kaars is zowel decoratief als functioneel en is ideaal om een gezellige sfeer te creëren in huis.",
        category: "Kaarsen",
        price: 1.5,
        format: "20 Centimeter",
        color: "turquoise - Paars",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: false,
        new: true,
        tokens: [
            "Kaars",
            "Zomerse Kaars",
            "Kaars turquoise",
            "Kaars Paars",
            "Kaars Paars met turquoise",
            "Kleurrijke kaars",
            "Vrolijke Kaars"
        ],
    }, 
    {
        code: "003",
        name: "Kaars Turquoise/Roze ",
        description:
        "Deze zelfgemaakte kaars heeft een unieke combinatie van Turquoise en Roze, die in elkaar overlopen en een prachtig visueel effect creëren wanneer ze brandt. De kaars is zowel decoratief als functioneel en is ideaal om een gezellige sfeer te creëren in huis.",
        category: "Kaarsen",
        price: 1.5,
        format: "20 Centimeter",
        color: "turquoise - Roze",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: true,
        new: true,
        tokens: [
            "Kaars",
            "Zomerse Kaars",
            "Kaars turquoise",
            "Kaars Roze",
            "Kaars Roze met turquoise",
            "Kleurrijke kaars",
            "Vrolijke Kaars"
        ],
    }, 
    {
        code: "004",
        name: "Kaars Turquoise/Wit Goud ",
        description:
        "Deze zelfgemaakte kaars heeft een unieke combinatie van Turquoise en Wit Goud, die in elkaar overlopen en een prachtig visueel effect creëren wanneer ze brandt. De kaars is zowel decoratief als functioneel en is ideaal om een gezellige sfeer te creëren in huis.",
        category: "Kaarsen",
        price: 1.5,
        format: "20 Centimeter",
        color: "Turquoise - Wit Goud",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: false,
        new: true,
        tokens: [
            "Kaars",
            "Zomerse Kaars",
            "Kaars turquoise",
            "Kaars Wit Goud",
            "Kaars Wit Goud met Turquoise",
            "Kleurrijke kaars",
            "Vrolijke Kaars"
        ],
    }, 
    {
        code: "005",
        name: "Oorbellen Turquoise ",
        description:
        "Voeg wat flair toe aan je outfit met deze prachtige oorbellen. Elk paar is uniek en met de hand gemaakt.",        
        category: "Oorbellen",
        price: 1.5,
        format: "20 Centimeter",
        color: "Turquoise - Goud",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: true,
        new: true,
        tokens: [
            "Oorbellen",
            "Moden",
            "Sierraden",
            "Blauwe Oorbellen",
            "Accesoires",
            "Kleurrijke Oorbellen",
            "Zelgemaakte oorbellen"
        ],
    }, 
    {
        code: "006",
        name: "Oorbellen Paars ",
        description:
        "Voeg wat flair toe aan je outfit met deze prachtige oorbellen. Elk paar is uniek en met de hand gemaakt.",        
        category: "Oorbellen",
        price: 1.5,
        format: "20 Centimeter",
        color: "Paars - Goud",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: false,
        new: true,
        tokens: [
            "Oorbellen",
            "Moden",
            "Sierraden",
            "Paarse Oorbellen",
            "Accesoires",
            "Kleurrijke Oorbellen",
            "Zelgemaakte oorbellen"
        ],
    }, 
    {
        code: "007",
        name: "Oorbellen Groen ",
        description:
        "Voeg wat flair toe aan je outfit met deze prachtige oorbellen. Elk paar is uniek en met de hand gemaakt.",        
        category: "Oorbellen",
        price: 1.5,
        format: "20 Centimeter",
        color: "Groen  - Goud",
        paper: "500 gram",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: false,
        new: true,
        tokens: [
            "Oorbellen",
            "Moden",
            "Sierraden",
            "Blauwe Oorbellen",
            "Accesoires",
            "Kleurrijke Oorbellen",
            "Zelgemaakte oorbellen"
        ],
    }, 
];
export default products;
