
export const PRODUCT_IMAGES_PREFIX = "/Productcode - ";
export const PRODUCT_IMAGES_FILE_TYPE = ".jpg";
export const products = [

        {
            code: "001",
            name: "Disk Oorbellen - Delfs Blauw",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige delfs blauwe oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Delfs Blauwe Oorbellen",
            price: 6.99,
            color: "Wit - Blauw",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Moden",
                "Sierraden",
                "Blauwe Oorbellen",
                "Accesoires",
                "Delfs Blauwe Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "002",
            name: "Bloem Oorbellen - Delfs Blauw",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige delfs blauwe oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Delfs Blauwe Oorbellen",
            price: 6.99,
            color: "Wit - Blauw",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Moden",
                "Sierraden",
                "Blauwe Oorbellen",
                "Accesoires",
                "Delfs Blauwe Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "003",
            name: "Ovaal Oorbellen - Delfs Blauw",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige delfs blauwe oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Delfs Blauwe Oorbellen",
            price: 6.99,
            color: "Wit - Blauw",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Moden",
                "Sierraden",
                "Blauwe Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "004",
            name: "Tube Oorbellen - Delfs Blauw",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige delfs blauwe oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Delfs Blauwe Oorbellen",
            price: 6.99,
            color: "Wit - Blauw",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Moden",
                "Sierraden",
                "Blauwe Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "005",
            name: "Kraal Oorbellen - Blauw Paars Turquoise",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Blauw - Paars - Turqouise",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "006",
            name: "Kraal Oorbellen - Geel Mint Groen Roze",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Geel - Mint Groen - Roze",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "007",
            name: "Kraal Oorbellen - Geel Turquoise Paars Blauw",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Geel - Turquoise - Paars - Blauw",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "008",
            name: "Kraal Oorbellen - Goud Oker Bronze",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Goud - Oker - Bronze",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "009",
            name: "Kraal Oorbellen - Paarse Mix",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Paars",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "010",
            name: "Kraal Oorbellen - Rood Roze Groen Geel",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Rood - Roze - Groen - Geel",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        }, 
        {
            code: "011",
            name: "Kraal Oorbellen - Roze Groen Goud Blauw Geel",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Roze - Groen - Goud - Blauw - Geel",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
        },
        { 
        code: "012",
        name: "Kraal Oorbellen - Roze",
        description:
        "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
        category: "Kraal Oorbellen",
        price: 9.99,
        color: "Roze",
        matriaal: "RVS",
        envelope: true,
        doubleSided: false,
        roundCorners: false,
        waterColor: false,
        favorite: false,
        new: true,
        tokens: [
            "Oorbellen",
            "Mode",
            "Sierraden",
            "Kleurvolle Oorbellen",
            "Accesoires",
            "Kleurrijke Oorbellen",
            "Zelgemaakte oorbellen"
        ],
        }, 
        { 
            code: "013",
            name: "Kraal Oorbellen - Blauw Wit Roze Goud",
            description:
            "Voeg wat flair toe aan je outfit met deze prachtige kraal oorbellen. Elk paar is uniek en met de hand gemaakt.",        
            category: "Kraal Oorbellen",
            price: 9.99,
            color: "Blauw - Wit - Roze - Goud",
            matriaal: "RVS",
            envelope: true,
            doubleSided: false,
            roundCorners: false,
            waterColor: false,
            favorite: false,
            new: true,
            tokens: [
                "Oorbellen",
                "Mode",
                "Sierraden",
                "Kleurvolle Oorbellen",
                "Accesoires",
                "Kleurrijke Oorbellen",
                "Zelgemaakte oorbellen"
            ],
            }, 
      
            {
                code: "014",
                name: "Dip Kaars - Geel Turquoise ",
                description:
                    "Deze zelfgemaakte kaars heeft een unieke combinatie van geel en turquoise, die in elkaar overlopen en een prachtig visueel effect creëren wanneer ze brandt. De kaars is zowel decoratief als functioneel en is ideaal om een gezellige sfeer te creëren in huis.",
                category: "Dip Kaarsen",
                price: 1.5,
                format: "A6",
                color: "Turquoise - Oranje",
                paper: "500 gram",
                envelope: true,
                doubleSided: false,
                roundCorners: false,
                waterColor: false,
                favorite: true,
                new: true,
                tokens: [
                    "Kaars",
                    "Zomerse Kaars",
                    "Kaars turquoise",
                    "Kaars Turquoise",
                    "Kaars Oranje met Turquoise",
                    "Kleurrijke kaars",
                ],
            },
        
              
    ];
    export default products;
    